language: go

go: 
  - 1.7
  - 1.8

before_script:
  - for d in $(go list ./... | grep -v vendor); do go vet $d; done

install:
  - go get ./...

script:
  - sh testAllPackages.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
