language: go

go: 
  - 1.8

before_script:
  - for d in $(go list ./... | grep -v vendor); do go vet $d; done

install:
  - go get -v -t ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export PATH=$PATH:$HOME/gopath/bin
  - sudo docker pull golang:1.8.1
  - sudo docker build --rm=true --file=test/integration/Dockerfile --tag=golook:latest .

script:
  - test/integration/run_integration_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
